server:
  port: 80


redis:
  host: localhost
  port: 6379
  timeout: 10
  pool-max-wait: 500
  pool-max-idle: 500
  pool-max-total: 1000



spring:
  application:
    # 应用名称
    name: text-online exam
  datasource:
    # 数据源名称
    name: defaultDataSource

  profiles:
    active: dev

setting:
  page:
    count: 6